openapi: 3.0.2
info:
  title: OpenLab App Service REST API
  description: This is a sample OpenLab application service REST API
  version: 0.0.1
  license:
    name: CC0 1.0
    url: https://creativecommons.org/publicdomain/zero/1.0/
servers:
  - url: https://api.openlab.run
paths:
  /v1/apps/{appname}:
    get:
      tags:
        - openlab
      summary: Get app information, endpoints and examples
      operationId: get_app_by_name
      parameters:
        - required: true
          schema:
            title: Appname
            type: string
          name: appname
          in: path
      responses:
        '200':
          description: App information, endpoints and examples
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/apps/{appname}/status/{jobid}:
    get:
      tags:
        - openlab
      summary: Get job metadata and status
      operationId: get_job_status
      parameters:
        - required: true
          schema:
            title: Appname
            type: string
          name: appname
          in: path
        - required: true
          schema:
            title: Jobid
            type: string
          name: jobid
          in: path
      responses:
        '200':
          description: Job metadata and status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/apps:
    get:
      tags:
        - openlab
      summary: List apps available on this service
      operationId: list_apps
      responses:
        '200':
          description: List of apps available on this service
          content:
            application/json:
              schema:
                title: Response 200 List Apps V1 Apps Get
                type: array
                items:
                  $ref: '#/components/schemas/App'
        '404':
          description: List of apps can't be found
  /v1/apps/{appname}/submit:
    post:
      tags:
        - openlab
      summary: Submit a new job request, receive job metadata and status
      operationId: submit_job
      parameters:
        - required: true
          schema:
            title: Appname
            type: string
          name: appname
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRequest'
      responses:
        '200':
          description: Job metadata and status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    App:
      title: App
      type: object
      properties:
        appname:
          title: Appname
          type: string
        description:
          title: Description
          type: string
        version:
          title: Version
          type: string
        endpoints:
          title: Endpoints
          type: array
          items:
            type: string
      description: App - an application in the Openlab network
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Job:
      title: Job
      required:
        - appname
        - jobid
      type: object
      properties:
        appname:
          title: Appname
          type: string
        inputs:
          title: Inputs
          type: array
          items:
            type: object
        parameters:
          title: Parameters
          type: object
        jobid:
          title: Jobid
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
        status:
          title: Status
          type: string
        outputs:
          title: Outputs
          type: array
          items: {}
      description: An Openlab job
    JobRequest:
      title: JobRequest
      type: object
      properties:
        appname:
          title: Appname
          type: string
        inputs:
          title: Inputs
          type: array
          items:
            type: object
        parameters:
          title: Parameters
          type: object
      description: a Request for an Openlab job
